---
title: "Plot3d boxesexample"
output: html_document
---

# Packages and setup

```{r}
if (requireNamespace("devtools", quietly = TRUE)) {
  devtools::load_all()
} else {
  warning(
    "Package {devtools} is not available.\n",
    "You need to manually load functions from the project's `R/` folder.\n",
    call. = FALSE
  )
}

library(scatterplot3d)

db <- get_sample_data()
```

# Data

```{r}
# Db used
if (requireNamespace("DT", quietly = TRUE)) {
  DT::datatable(db) 
} else {
  db
}


processed_db <- summarize_3d(db)
processed_db
```

## Estract info

```{r}
processed_db <- summarize_3d(db)

min_object <- prepare_3d(
  processed_db[c("X_min", "Y_min", "Z_min")]
)
min_object

main_object <- prepare_3d(
  processed_db[c("dim_max", "dim_med", "dim_min")]
)
  
main_object

max_object <- prepare_3d(
  processed_db[c("X_max", "Y_max", "Z_max")]
)
max_object
```

# 3D Plot

```{r, webgl=TRUE}
segments <- list(
  a = c("A", "B"),
  b = c("B", "D"),
  c = c("D", "C"),
  d = c("C", "A"),
  e = c("E", "F"),
  f = c("F", "H"),
  g = c("H", "G"),
  h = c("G", "E"),
  i = c("A", "E"),
  j = c("B", "F"),
  k = c("C", "G"),
  l = c("D", "H")
)

scr <- scatterplot3d::scatterplot3d(
  x = max_object[[1]],
  y = max_object[[2]],
  z = max_object[[3]], 
  color = "red",
  xlab = "Largest dimension",
  ylab = "Medial dimension",
  zlab = "Smallest dimension",
  asp = 1,
  scale.y = max(max_object[[2]]) / max(max_object[[1]]),
  box = FALSE,
  type = "n"
)

for (segment in segments) {
  add_segment(scr, max_object, segment, "red")
  add_segment(scr, main_object, segment, "blue")
  add_segment(scr, min_object, segment, "green")  
}



title(
  "Boxes of target and reference objects",
  sub = "Points for target (blu), and largest (red) and smallest (green) in the category."
)
```


# System Info
<details>
  <summary>Click for System Info</summary>
```{r, echo = FALSE}
if (requireNamespace("devtools", quietly = TRUE)) {
  devtools::session_info()
} else {
  Sys.info()
  loadedNamespaces()
}
```
<details>

